- index.js
- test/index.js
Checks if a given language code is known to the library database.
> Add isKnown method

- data/langdb.yaml
- language-data.json
Requested at
https://phabricator.wikimedia.org/T176157
> Add Guianan Creole

- data/langdb.yaml
- language-data.json
For consistency with https://phabricator.wikimedia.org/T190205
> Lowercase autonym for ku-latn

- data/langdb.yaml
- language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Colville-Okanagan_Salish
Autonym spelling according to
http://www.interiorsalish.com/images/ns_601_lxcin_1_book_3rd_Ed_Vers_2.pdf
> Add Okanagan language

- data/langdb.yaml
- language-data.json
There's a Wikipedia Incubator in this language,
so it should be included.
> Add Northern Ndebele

- data/langdb.yaml
- language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Please_activate_Mandailing_language
> Add Mandailing language (btm)

- index.js
- test/index.js
A step to resolving downstream bug:
https://phabricator.wikimedia.org/T189090
> Add sortByScriptGroupAndAutonym

- data/langdb.yaml
- language-data.json
Ref: https://translatewiki.net/wiki/Summary:Support/Request:_Enabling_Kaqchikel
> Add Kaqchikel (cak)

- data/langdb.yaml
- language-data.json
Requested on https://translatewiki.net/wiki/Thread:Support/Request:_Enable_Malay_(Arabic)_language_translations
> Add Malay in Arabic script (ms-Arab)

- package.json
* Update version of eslint from 2.9.0 to 5.16.0.
* Update version of mocha from 2.5.3 to 6.1.4.
> Update package.json to fix npm audit recommendations

- data/langdb.yaml
- language-data.json
Requested at
https://translatewiki.net/wiki/Thread:User_talk:Amire80/Please_Activate_Rejang_Language_Localisation
> Add Rejang

- data/langdb.yaml
- language-data.json
Part of downstream bug https://phabricator.wikimedia.org/T223544.
> Update native language name of Skolt Sami

- data/langdb.yaml
- language-data.json
Per https://phabricator.wikimedia.org/T226701#5371251
> Update autonym for sju

- data/langdb.yaml
- language-data.json
> Change autonym "using" to "Using"

- composer.json
- package.json
- src/util/ulsdata2json.php
Also update authors to be alphabetically ordered.
> Add users with more than 5 commits to credits / authors

- package-lock.json
Done automatically by npm audit fix
> Update acorn version in package-lock.json

- src/util/ulsdata2json.php
> Fix incorrect data directory usage in ulsdata2json.php

- data/langdb.yaml
- data/language-data.json
No need for a capital letter there.
> Change spelling of Innu-aimun autonym

- .github/workflows/php.yml
- .gitignore
- composer.json
- phpunit.xml
- src/LanguageUtil.php
- tests/php/LanguageUtilTest.php
Use the configuration file to pass the location of the tests and
autoload class files.
Pass `-sp` to `phpcs` command
> Add phpunit configuration file

- data/langdb.yaml
- data/language-data.json
Requested at
https://lists.wikimedia.org/pipermail/wikipedia-l/2020-June/031951.html
> Add Nuxalk language

- CHANGELOG.md
- package.json
Also update npm package version to 0.2.1
> Add Changelog for 2020-07 release

- package.json
Fixes: #115
Tested by installing the package: 
`npm install wikimedia/language-data#add-entrypoint`
> Add entrypoint in package.json

- composer.json
- composer.lock
> Update mediawiki-codesniffer to 31.0.0

- .github/workflows/node.yml
- package-lock.json
- package.json
- src/index.js
Had to update eslint to ^7.9.0 since we are using new rules:
* no-loss-of-precision
* no-unreachable-loop
Bug: T266462
> Bump eslint-config-wikimedia to 0.17.0

- CHANGELOG.md
> Update Changelog for 2020.10 release

- data/langdb.yaml
- data/language-data.json
Requested at https://translatewiki.net/wiki/Support ,
but I cannot link to the request as it had to be
deleted because of a LiquidThreads bug.
> Add Nuer language (nus)

- data/langdb.yaml
- data/language-data.json
> Change lmo language name

- package-lock.json
> Security fix: Update glob-parent to 5.1.2

- CHANGELOG.md
- package-lock.json
- package.json
> Add release notes 2021.07

- data/langdb.yaml
- data/language-data.json
Requested for translatewiki at
https://translatewiki.net/wiki/Thread:Support/Adding_a_new_language_-_Lologooli
There are several variants of the autonym online.
The images at https://lologooli.org/ show that "Lologooli"
is probably a good variant, at least for starters.
> Add Logooli (rag)

- data/langdb.yaml
- data/language-data.json
Requested for translatewiki at:
https://translatewiki.net/wiki/Thread:Support/Adding_a_new_language
Autonym verified at
https://www.alaskanativelanguages.org/unangam-tunuu
> Add Aleut languages

- data/langdb.yaml
- data/language-data.json
According to the discussion in translatewiki:
https://translatewiki.net/wiki/Thread:User_talk:Karapananguas%C3%BA_Kurur%C3%BA_Terememb%C3%A9/Language_name
> Update Nheengatu (yrl) autonym

- data/langdb.yaml
- data/language-data.json
Requested at
https://en.wikipedia.org/w/index.php?title=User_talk:Amire80&oldid=1065825851#Translate_wiki_registration
> Add the Nyankore language (nyn)

- composer.json
- composer.lock
- src/LanguageUtil.php
- tests/php/LanguageUtilTest.php
Update the following dependencies:
* php-unit
* mediawiki-codesniffer
Use specific dependencies.
Fix issues highlighted by new rules in mediawiki-codesniffer
> Update composer dependencies

- CHANGELOG.md
- package-lock.json
- package.json
> Add release notes for 2022.01

- data/language-data.json
I forgot to run this in my last update.
> Run ulsdata2json.php

- package-lock.json
Audotmatically by `npm audit fix`.
> Bump minimist version

- data/langdb.yaml
- data/language-data.json
Requested for translatewiki at
https://translatewiki.net/wiki/Thread:Talk:Support/Activate_new_language:_Efik_(efi)
> Add Efik (efi)

- data/langdb.yaml
- data/language-data.json
"Kokborok" is enough as the name, and the alias is not needed.
> Change trp autonym

- data/language-data.json
Pakistan regional data: remove tg-cyrl and reorder
some other languages.
> Auto-update language-data.json

- composer.json
- composer.lock
- tests/php/LanguageUtilTest.php
Ran composer show --outdated and then composer update after updating
package.json
Fix CI failures:
* assertEmpty performs loose comparisons and should not be used.
> Update PHP dependencies

- data/langdb.yaml
- data/language-data.json
Requested for Wikipedia at
https://lists.wikimedia.org/hyperkitty/list/wikipedia-l@lists.wikimedia.org/thread/KODM5QNNLIKKC4THHQNJHBH3PME3YQJ7/
> Add Wolaytta (wal)

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Please_add_the_Kalanga_Language
> Add Kalanga (kck)

- data/langdb.yaml
- data/language-data.json
I wrote the capital letter by mistake. It's not necessary.
> Fix Wolaytta autonym

- data/langdb.yaml
- data/language-data.json
I wrote the capital letter by mistake. It's not necessary.
> Fix Bunun autonym

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Request_to_Add_New_Language
> Add Esan language

- data/langdb.yaml
- data/language-data.json
Verified with Ethnologue, https://www.inupiaqonline.com dictionary,
and other sources.
Downstream bug report:
https://phabricator.wikimedia.org/T315406
> Fix the autonym of the Iñupiaq language

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Enable_aae:_Arb%C3%ABrisht
> Add Arbëresh language (aae)

- .github/workflows/php.yml
- composer.json
- composer.lock
> Drop support for PHP 7.2, and update dependencies

- CHANGELOG.md
- package-lock.json
- package.json
Bug: https://phabricator.wikimedia.org/T326539
> Add language-data release notes 2023.01

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/w/i.php?oldid=11512120#Request_for_inclusion_of_Ibibio_language
Authonym according to Ethnologue.
> Add Ibibio (ibb)

- package-lock.json
- package.json
npm outdated output:
```
Package  Current  Wanted  Latest  Location             Depended by
eslint    8.32.0  8.32.0  8.38.0  node_modules/eslint  language-data
```
npm update output:
```
added 1 package, removed 3 packages, changed 23 packages, and audited 262 packages in 2s
```
Bug: https://phabricator.wikimedia.org/T333823
> Node: Update dependencies

- CHANGELOG.md
- package-lock.json
- package.json
Bug: https://phabricator.wikimedia.org/T333823
> Update Changelog file and version in package.json

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/w/i.php?title=Support&oldid=11570972
> Add Crimean Tatar (Romania)

- data/langdb.yaml
- data/language-data.json
Addresses downstream issue
https://phabricator.wikimedia.org/T256647
The spelling and the capitalization are according to "New Choctaw Dictionary", 2016
https://choctawschool.com/media/369055/New%20Choctaw%20Dictionary.pdf
> Correct Choctaw autonym

- data/langdb.yaml
See https://translatewiki.net/w/i.php?title=User_talk:Bangrapip&oldid=11652488
> Update Betawi (bew) autonym

- data/language-data.json
Sorry, I forgot to do it in #300.
> Run src/util/ulsdata2json.php

- composer.json
- composer.lock
```
Package operations: 0 installs, 3 updates, 0 removals
- Downloading phpunit/phpunit (9.6.10)
- Upgrading sebastian/diff (4.0.4 => 4.0.5): Extracting archive
- Upgrading nikic/php-parser (v4.15.4 => v4.16.0): Extracting archive
- Upgrading phpunit/phpunit (9.6.7 => 9.6.10): Extracting archive
```
Bug: https://phabricator.wikimedia.org/T340730
> PHP: Update dependencies

- data/langdb.yaml
- data/language-data.json
Requested for translatewiki at
https://translatewiki.net/w/i.php?title=Support&oldid=11766863#New_language:_Pintupi-Luritja
> Add Pintupi-Luritja

- package-lock.json
- package.json
It appears to be included in Mocha.
> Remove assert from package.json

- data/langdb.yaml
- data/language-data.json
Updated `langdb.yaml` and `language-data.json`
Bug: T333765
> Remove akan

- data/language-data.json
Add some languages to territories.
> Autoupdate language-data.json

- package-lock.json
semver  7.0.0 - 7.5.1
Severity: moderate
semver vulnerable to Regular Expression Denial of Service - https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
> Node: Fix npm audit issues

- CHANGELOG.md
- package-lock.json
- package.json
Bug: https://phabricator.wikimedia.org/T347849
> Add release notes and update npm versions

- data/langdb.yaml
- data/language-data.json
Recently added to translatewiki.
> Add Western Apache

- data/langdb.yaml
- data/language-data.json
Requested at https://translatewiki.net/w/i.php?title=Support&oldid=12184726#Add_Nupe_language
> Add Nupe (nup)

- composer.json
> composer.json: Add ext-curl to dev dependencies

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T356104
> Add Ebira (igb)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T356248
> Add Petjoh (pey)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T361989
Also automatically removes Toki Pona from Canada
and Volapuk from Gemrany.
> Add Iban (iba)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T368857
> Add Edo (bin)

- .github/workflows/node.yml
Hopefully addresses deprecation warnings
> Update node action versions

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T368858
> Add Waalii (wlx)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T369095
> Add Jakalteko (jac)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T369157
> Add Kihunde (hke)

- data/langdb.yaml
- data/language-data.json
See the discussion at
https://translatewiki.net/w/i.php?title=User_talk:Suitcaseshoes&oldid=12502190 (especially towards the bottom).
This name is also verified using 2001 dictionary
published by SIL.
> Make a less ambiguous autonym for acf

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T369578
> Add Torwali (trw)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T369464
> Add Abron (a.k.a. Bono, Brong, abr)

- CHANGELOG.md
Bug: https://phabricator.wikimedia.org/T369065
> Add some more language updates in changelog

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T371985
> Add Ngiemboon (nnh)

- data/language-data.json
Reorder yue-hans and add ro to U.K.
> Auto-update regional data

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T375535
> Add Khoekhoe (a.k.a. Nama, naq)

- data/langdb.yaml
- data/language-data.json
Downstream task: 
https://phabricator.wikimedia.org/T375891
> Update Kadazan Dusun (dtp) autonym

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T377797
> Add Mampruli (maw)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T377851
> Add Maguindanaon (mdh)

- data/language-data.json
> Update regional information automatically

- data/langdb.yaml
- data/language-data.json
Downstream tasks:
https://phabricator.wikimedia.org/T379870
https://phabricator.wikimedia.org/T380246
> Add Bamum (bax, bax-bamu) and Likpakpaanl (Konkomba; xon)

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T383038
> Add Lampung Api (ljp)

- data/langdb.yaml
- data/language-data.json
To reduce the hance of confusion with pap.
https://phabricator.wikimedia.org/T389644
> Change pap-aw autonym

- data/langdb.yaml
- data/language-data.json
Downstream task: https://phabricator.wikimedia.org/T392242
> Add Sasak (sas)

- data/langdb.yaml
- data/language-data.json
Downstream task: https://phabricator.wikimedia.org/T392266
> Add Michif (crg)

- data/langdb.yaml
- data/language-data.json
Downstream task: https://phabricator.wikimedia.org/T394068
> Add Puno Quechua (qxp)

- data/langdb.yaml
- data/language-data.json
- tests/php/LanguageUtilTest.php
Downstream task: https://phabricator.wikimedia.org/T394873
> Fix redirects for az and azb languages

- data/langdb.yaml
- data/language-data.json
Downstream task: https://phabricator.wikimedia.org/T392255
> Add Rajasthani (raj)

- data/langdb.yaml
- data/language-data.json
Added territories based on ethnologue data: https://www.ethnologue.com/language/aig/
Task: https://phabricator.wikimedia.org/T397356
> Add aig to language data

- package-lock.json
Automatic update of package-lock.json.
> Run npm audit fix 2025-06-30
