wikimedia/language-data

- data/langdb.yaml
- language-data.json
Requested at translatewiki:
https://translatewiki.net/wiki/Thread:Support/support_for_Huaylas_Ancash_Quechua
Source for autonym spelling:
http://www.illa-a.org/wp/diccionarios/
> Add qwh (Ancash Quechua)

- data/langdb.yaml
- language-data.json
This was somehow missed, even though it's already supported
in MediaWiki's Names.php, and there's a Wikipedia in it.
> Add Gorontalo language (gor)

- data/langdb.yaml
- language-data.json
Changed the name of the (gcr) language from "Kreyol Gwiyanè" to "Kriyòl Gwiyannen"
Per: https://translatewiki.net/wiki/Thread:Support/Need_Help_!
> Changed the name of the gcr language

- data/langdb.yaml
- language-data.json
The word "Basa" simply means "language" and it is unnecessary.
This was requested at the Javanese Wikipedia village pump:
https://jv.wikipedia.org/w/index.php?title=Wikipedia:Warung_Kopi&oldid=1478057#Jawa_utawa_Basa_Jawa
> Change the autonym of Javanese from "Basa Jawa" to "Jawa"

- data/langdb.yaml
- language-data.json
Addresses downstream issue
https://phabricator.wikimedia.org/T224806
This was already changed in MediaWiki core.
> Rename "Baso Minangkabau" to "Minangkabau"

- data/langdb.yaml
- language-data.json
This also adds the support for the Meetei Mayek script
(ISO 15924: Mtei) to langdb.
Meetei Mayek script is the one used in schools in Manipur
(see the Wikipedia article [[Meitei script]] for references).
It is also the script that is used for all the translations
in translatewiki [1] and for all the test articles
in the Wikimedia Incubator.[2]
The Bengali script version is preserved with a tag,
because the Bengali script may be used as well.
[1] https://translatewiki.net/w/i.php?title=Special:Translate&filter=translated&group=mediawiki&language=mni&action=translate
[2] https://incubator.wikimedia.org/wiki/Special:PrefixIndex/wp/mni
> Change the autonym of Manipuri to Meetei script

- data/langdb.yaml
- language-data.json
It is already in MediaWiki, but for some reason it
was never added to ULS.
> Add Awadhi (awa)

- data/langdb.yaml
- language-data.json
Requested at
https://www.wikidata.org/wiki/Wikidata_talk:Lexicographical_data#Spelling_variant_of_the_Lemma_option
> Add Bajau Sama language (bdr)

- language-data.json
This removes szy and shy from language-data.json,
which are not standard in CLDR for the territories.
They should be added differently.
> Run ulsdata2json.php

- package.json
Fixes failing test case on node.js version 6.
```
> @wikimedia/language-data@0.1.2 test /home/abijeet/Development/Projects/php/code/language-data
> mocha tests/js/*.js
languagedata
✓ language tags
✓ autonyms
1) regions and groups
✓ scripts
✓ redirects
✓ directionality
5 passing (20ms)
1 failing
1) languagedata
regions and groups:
AssertionError: languages in region AM are ordered correctly by script group
+ expected - actual
"qu"
"srn"
"chy"
"yi"
-  "chr"
"ike-cans"
"cr"
+  "chr"
]
at Context.<anonymous> (tests/js/index.js:129:10)
npm ERR! Test failed.  See above for more details.
```
> Update minimum supported node.js version to 8.x

- package-lock.json
- package.json
This fixes all npm audit warnings.
> Set latest and specific versions of devDependencies

- data/langdb.yaml
- data/language-data.json
Making Sylo the default, because that's the only one used at translatewiki and Wikimedia Incubator.
> Add Sylheti

- CHANGELOG.md
- README.md
- docs/index.rst
Divide the changelog into - Language updates, PHP and Node.js section
PHP and Node.js changelog will list library related changes and will
reuse Language updates section.
Add the release schedule to the README file.
Bug: T218639
> Add changelog and release schedule

- data/langdb.yaml
- data/language-data.json
This is needed for better support of the Wikipedia Incubator
( https://incubator.wikimedia.org/wiki/Wp/mad )
and translatewiki.
Autonym spelling according to this dictionary:
Adrian Pawitra, "Kamus lengkap bahasa madura—indonesia"
(The title is in Indonesian and hence spelled differently.)
> Add Madurese (mad)

- data/langdb.yaml
- data/language-data.json
According to "Pedoman Umum Ejaan Bahasa Madura yang Disempurnakan" (2008, page 8),
names of languages are supposed to be written with capital letters.
Online book:
http://repositori.kemdikbud.go.id/1761/1/Ejaan%20Bahasa%20Madura%20Yang%20Disempurnakan%20%282008%29.pdf
> Change Madurese autonym to capital

- package-lock.json
See: https://github.com/advisories/GHSA-p6mc-m468-83gw
> Update lodash to 4.17.19

- .github/workflows/node.yml
- package.json
In a subsequent patch #120, we bump eslint-config-wikimedia to
0.17.0, which also requires bumping eslint to 7.9.0 which drops
support for Node.js 8.x
Bug: T266462
> Bump minimum Node.js version to 10.x

- data/langdb.yaml
- data/language-data.json
Originally written by yjfvictor at
https://github.com/wikimedia/language-data/pull/58
Updated more conservatively by Amir E. Aharoni.
This is probably a transition to allow the splitting
to two variants. "cdo" will be reconfigured later
once the transition in other MediaWiki-related
properties will be over.
> Update Min Dong Chinese languages

- .github/workflows/php.yml
Pin image to specific version so that we don't get surprise failures down the line.
Use common action to configure the default PHP version. The matrix versions only affected test running. Now it affects everything.
Only use PHP 7.4 as 8.0 does not pass.
> Fix PHP builds

- tests/js/index.js
The reason I'm adding it is that recently I almost submitted
a patch in which I wrote a language code with the Cyrillic letter о
instead of the corresponding Latin letter. It's not a perfect test,
but it's good enough for a basic check.
> Add a simple test for validity of language codes

- data/langdb.yaml
- data/language-data.json
This language is known in English as Shilha, Tashelhit,
Tachelhit, and also by some other names.
The most authoritative modern name in the language itself
is Taclḥit, with the letter c. It appears in the textbook
"Méthode de tachelhit, langue amazighe (berbère) du sud du Maroc"
by Abdallah El Mountassir and also in the online
"Dictionnaire Général de la Langue Amazighe Informatisé"
( https://tal.ircam.ma/dglai/lexieam.php ). It also directly
corresponds to the spelling in the Tifinagh script.
This change was requested by the localizers in translatewiki
and authors in the Wikipedia Incubator in this language.
> Update the autonym of language shi

- data/language-data.json
This is added automatically by `php ulsdata2json.php`.
It should have been added in #137, but for some reason wasn't.
> Add Rohg to rtlscripts

- data/langdb.yaml
- data/language-data.json
In the years that have passed since I wrote a comment saying
that this language is "complicated", I found sources that clearly
show that the primary alphabet for this language now is Latin.
See https://en.wikipedia.org/wiki/Talysh_language#Scripts
MediaWiki's Names.php was updated, too.
> Cleanup the data for the Talysh language

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Support#Activate_new_language-code:_Papiamento_(pap-aw)_58665
The name "Papiamento" (with -o) is used in the standard Aruba
spelling, and the -o in the end in enough for speakers to recognize
as the Aruban variant.
> Add Aruba Papiamento

- data/langdb.yaml
- data/language-data.json
The name "Wayúu" appeared a long time ago in translatewiki,
and it's unclear what is its source. All the sources that I can
find say that autonym is "wayuunaiki", for example Ethnologue and
Diccionario básico ilustrado wayuunaiki-español español-wayuunaiki
(Editorial Fundación para el Desarrollo de los Pueblos Marginados, Bogotá, D.C., 2005)
> Update the autonym for guc

- src/util/ulsdata2json.php
This helps Git and Vim be less confused about diffs.
It somehow sometimes happens that a newline is added to
the end of language-data.json, but sometimes it is not added,
and then Git diff shows it as removed or added. This change
ensures that it's always added.
> Add a newline to the end of language-data.json

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Template_talk:Disabled_language/Enabling_Belizean_Creole
> Add Belizean Creole (bzj)

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Talk:Support/Ajouter_la_langue_bassa%27a
Autonym according to
Hyman, Larry M. (2003). "Basaá (A.43)".
In Nurse, Derek; Philippson, Gérard (eds.).
The Bantu Languages. Routledge. pp. 257–282.
> Add the Basaa language (bas)

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Please_add_the_Kom_language
Autonym as used in the introduction to
Provisional Kom - English Lexicon by Randy Jones (2001),
and confirmed by a native speaker.
> Add the Kom language (bkm)

- package-lock.json
Fixes CVE-2020-7774
Not a major issue for us since it's only a dev dependency.
> Fix y18n (required by mocha) related security warning

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Dargin_language
Autonym according to:
Х.ГӀ. Юсупов, «Даргала-урусла словарь», ХӀ. ЦӀадасала уличилси
Мезла, литературала ва искусствола институт, МяхIячкъала 2014
and verified with speakers.
> Add the Dargin (Dargwa) language (dar)

- CHANGELOG.md
Reusing the release made on 2021.04.01 for Node.js library security
fix.
> Update changelog for 2021.04 release

- data/langdb.yaml
- data/language-data.json
Will hopefully address these downstream bugs:
https://phabricator.wikimedia.org/T279269
https://phabricator.wikimedia.org/T279252
> Make 'ha' the primary code for Hausa

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/_Wp/pwn_Translation_of_MediaWiki_(most_important_messages)
Autonym verified with Paiwan dictionary by Raliegh Ferrell
( https://archive.org/details/paiwandictionary0000ferr )
and the online dictionary on the website of Taiwan's
Council of Indigenous People
( https://e-dictionary.apc.gov.tw/pwn/search.htm ).
It's also confirmed at
https://incubator.wikimedia.org/w/index.php?oldid=5144344#The_name_of_the_Paiwan_language_in_itself
> Add the Paiwan language (pwn)

- data/language-data.json
It was added to Language-Territory information in CLDR 39,
and automatically added here by the updating script.
> Add Rohingya as a language of Bangladesh and Burma

- .github/workflows/node.yml
- package-lock.json
- package.json
Following packages have been updated:
* eslint
* eslint-config-wikimedia
* mocha
Also use specific version of packages in order to avoid
potential issues on update.
> Update npm modules and drop support for Node.js 10

- data/langdb.yaml
- data/language-data.json
The code `tokipona` is not a valid ISO code. This week Toki Pona received a valid ISO code: `tok`. This can be verified [here](https://iso639-3.sil.org/code/tok) and [here](https://iso639-3.sil.org/request/2021-043). This pull request changes `tokipona` to `tok`.
The correct autonym for Toki Pona is `toki pona`. In Toki Pona, all native words are written in lowercase. Check [page 3 of the ISO request](https://iso639-3.sil.org/sites/iso639-3/files/change_requests/2021/2021-043_tok.pdf#page=3) for a source.
> Update Toki Pona

- data/langdb.yaml
- data/language-data.json
The name "Kirundi" was added to MediaWiki very early in
its history. This name is used in English (in addition to "Rundi"),
but the native name is actually "ikirundi". It appears in Ethnologue.
See also
https://phabricator.wikimedia.org/T302972
> Fix the autonym for Rundi (rn)

- data/langdb.yaml
- data/language-data.json
It has been mistakenly defined as "ME, EU" since langdb was created.
> Fix the geo data of Karay-a (krj)

- data/langdb.yaml
- data/language-data.json
"Eastern" Yiddish is much more common than Western, so ydd
and yi refer to the same language. It's unclear why was ydd
even added to translatewiki. It was done very long ago,
before translatewiki configuration was managed in Git.
There are no translation into it there, which makes sense,
given that it's the same as just Yiddish (yi).
Given that ydd is a standard code, it can remain as
a redirect, but it shouldn't really be used.
> Redirect "Eastern Yiddish" (ydd) to Yiddish (yi)

- data/langdb.yaml
- data/language-data.json
It was there by mistake. It's definitely just in Europe.
> Remove Livvi Karelian from Asia

- data/langdb.yaml
- data/language-data.json
Correct it to be the same as in MediaWiki core.
Spelling verified in
Iriza Kinyarwanda Engish And English Kinyarwanda Dictionary.
> Update Kinyarwanda autonym

- data/langdb.yaml
- data/language-data.json
In Kanuri, the name of the language is specifically
written in lowercase, according to
"Dictionary of the Kanuri Language"
Edited by: Norbert Cyffer and John Hutchinson
De Gruyter 1990.
> Change Kanuri autonym to lowercase

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/wiki/Thread:Support/Request_to_reactivate_Makassarese_to_Translatewiki
Autonyms in Latin and Lontara script according
to page 187 in this dictionary:
Kamus Makassar-Indonesia, Drs. Aburaerah Arief, 1995
Comment: It appears that there are two spelling standards.
In the other one, the name is written with an apostrophe
instead of the letter k in the end. The one with k appears to be
the common one in Indonesian publications, and is
used in the Wikimedia Incubator. If the speakers' community
ever decides to move the spelling with the apostrophe,
the name can be changed.
> Add Makassarese (mak)

- data/langdb.yaml
- data/language-data.json
In use in Wikidata for monolingual text [1] and lexemes [2].
For the autonyms, see [3], an online dictionary by the Lia Rumantscha, an umbrella organisation of Romansh language organisations and the dialects section of [4], an article about Romansh in e-LIR, which is a Romansh encyclopedia about the Romansh speaking area of Switzerland. Puter is sometimes written "putèr", as noted in [5], but all three sites just mentioned use "puter".
Wikidata items:
Puter: https://www.wikidata.org/wiki/Q688309
Rumantsch Grischun: https://www.wikidata.org/wiki/Q688873
Surmiran: https://www.wikidata.org/wiki/Q690216
Sursilvan: https://www.wikidata.org/wiki/Q688348
Sutsilvan: https://www.wikidata.org/wiki/Q688272
Vallader: https://www.wikidata.org/wiki/Q690226
[1] …
> Add Romansh variants

- data/langdb.yaml
- data/language-data.json
In use in Wikidata for monolingual text [1] and lexemes [2]. For the autonym, see Dictionnaire Français-Monégasque [3] by the Comité National des Tradtions Monégasques and a page about the language [4] by the Académie des Langues Dialectales (Monaco).
Wikidata item: https://www.wikidata.org/wiki/Q56422
[1] https://github.com/wikimedia/Wikibase/blob/425d9d47794b1e36a792be0180dd7f8d63bc6418/lib/includes/WikibaseContentLanguages.php#L144
[2] https://github.com/wikimedia/mediawiki-extensions-WikibaseLexeme/blob/548ead57fa89125962425efd6268d5c040353532/WikibaseLexeme.mediawiki-services.php#L27
[3] http://www.traditions-monaco.com/dictionnaire-francais-monegasque
[4] http://www.ald-monaco.org/langues-monegasque/la-langue-monegasque-son-origine-et-sa-typologie-6
> Add Monégasque (lij-mc)

- data/langdb.yaml
- data/language-data.json
The apostrophe-like character in the name is a letter called ʻokina [1].
[1] https://en.wikipedia.org/wiki/ʻOkina
> Fix Hawaiian (haw) autonym

- .github/workflows/node.yml
- package-lock.json
- package.json
Latest version of ESLint no longer supports v12.0.0 that went EOL in April, 2022
Add Node.js 18.0.0 to CI. 
Additionally update dependencies. npm outdated showed the following:
* eslint - 8.26.0 --> 8.32.0
* eslint-config-wikimedia - 0.23.0 --> 0.24.0
* mocha - 10.1.0 --> 10.2.0
> Drop support for Node.js 12 and update dependencies

- data/langdb.yaml
- data/language-data.json
In use in Wikidata for labels, monolingual text and lexemes [1].
[1] https://gerrit.wikimedia.org/r/plugins/gitiles/operations/mediawiki-config/+/f7c596ad7737cd266edffa7f6c20916436ce586e/wmf-config/InitialiseSettings.php#21869 (large page)
> Add American English (en-us)

- data/langdb.yaml
- data/language-data.json
In use in Wikidata for monolingual text [1] and lexemes [2]. For the autonym of Jèrriais, see [3] by the Société Jersiaise and the website Les Pages Jèrriaises [4]. For the autonym of Guernésiais, see [5] from gov.gg and [6] from BBC Guernsey. [7] from the Guernsey Language Commission, although in English, uses the same spelling.
Wikidata item for Jèrriais: https://www.wikidata.org/wiki/Q56430
Wikidata item for Guernésiais: https://www.wikidata.org/wiki/Q56428
[1] https://github.com/wikimedia/Wikibase/blob/425d9d47794b1e36a792be0180dd7f8d63bc6418/lib/includes/WikibaseContentLanguages.php#L144
[2] https://github.com/wikimedia/mediawiki-extensions-WikibaseLexeme/blob/548ead57fa89125962425efd6268d5c040353532/WikibaseLexeme.mediawiki-services.php#L27
[3] …
> Add Jèrriais (nrf-je) and Guernésiais (nrf-gg)

- data/language-data.json
Mostly cosmetic changes. Adds CQ territory for backwards compatibility,  moves the placement of lmo and apc in the lists, and adds apc for Turkey.
> Automatic update of region data

- composer.json
- composer.lock
- phpunit.xml
Output of composer outdated:
```
Direct dependencies required in composer.json:
mediawiki/mediawiki-codesniffer v39.0.0 v41.0.0
phpunit/phpunit                 9.5.25  9.6.7
Transitive dependencies not required in compose
myclabs/deep-copy               1.11.0  1.11.1
nikic/php-parser                v4.15.3 v4.15.4
phpunit/php-code-coverage       9.2.23  9.2.26
sebastian/environment           5.1.4   5.1.5
sebastian/recursion-context     4.0.4   4.0.5
sebastian/type                  3.2.0   3.2.1
squizlabs/php_codesniffer       3.6.2   3.7.2
```
Manually updated phpunit and mediawiki-codesniffer. 
Update phpunit.xml file as per latest format.
Bug: https://phabricator.wikimedia.org/T333823
> PHP: Update dependencies

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/w/i.php?title=Support&oldid=11615943#Request_for_inclusion_of_Brazilian_Sign_Language
The name is written in Portuguese. This is similar to how it's done with American Sign Language (ase), which uses an English "autonym", and that's also what
was requested for the Brazilian Sign Language.
> Add Brazilian Sign Language

- data/langdb.yaml
- data/language-data.json
The language was added long ago with an English name.
Source for the correct autonym:
https://apics-online.info/contributions/50
> Update the autonym for Guadeloupean Creole (gcf)

- data/langdb.yaml
- data/language-data.json
Script variants for Serbo-Croatian have been added to Names.php [1] as part of the changes for adding a language converter [2].
[1] https://gerrit.wikimedia.org/r/plugins/gitiles/mediawiki/core/+/a573bea01b7f05186324327cbcdf804644b863d2/includes/languages/data/Names.php#422
[2] https://phabricator.wikimedia.org/T268033
> Add script variants for Serbo-Croatian (sh-cyrl and sh-latn)

- package-lock.json
- package.json
Fixes some audit issues, some remain but that's OK since these are just dev dependencies.
Remaining issue:
```
semver  7.0.0 - 7.5.1
Severity: moderate
https://github.com/advisories/GHSA-c2qf-rxjj-qqgw
fix available via `npm audit fix --force`
Will install eslint-config-wikimedia@0.17.0, which is a breaking change
```
Bug: https://phabricator.wikimedia.org/T340730
> Node: Update dependencies

- data/langdb.yaml
- data/language-data.json
Both were recently added to translatewiki.
Bole autonym according to the review article
Schuh, Russell G. (October 1996).
"Dymitr Ibriszimow and Alhaji Maina Gimba (ed.):
Bole language and documentation Unit (BOLDU), Report I." Bulletin of the School of Oriental and African Studies. 59 (3): 620–621.
Karekare autonym according to the book
"Dindeno, asumka waɗo mabo Karai-karai"
Yobe Languages Research Project 2009
https://ucla.app.box.com/s/xvpgk2ecl73nwnjyyo7g80fsr96mtsbz
> Add Bole (bol) and Karekare (kai)

- data/langdb.yaml
- data/language-data.json
Add the Komering language (Latin and Arabic scripts), recently added to Translatewiki.net. Autonyms according to Wikipedia and requester on Translatewiki.net.
> Add Komering

- .github/workflows/node.yml
- package-lock.json
- package.json
* eslint 8.56.0 --> 8.57.0 (No longer supports Node.js 14)
* eslint-config-wikimedia 0.26.0 --> 0.27.0
* mocha 10.2.0 --> 10.4.0
Drop Node.js 14 support, and add support for Node.js 20.
Bug: https://phabricator.wikimedia.org/T360422
> Update npm dependencies, drop Node.js 14 support

- data/langdb.yaml
- data/language-data.json
Manchu (mnc) should be added to Names.php [1] but the translations are a mixture of Latin and Mongolian scripts and need to be split [2]. For the autonym, see the existing translations [3] and the main page of the Manchu Wikipedia in the Incubator [4].
[1] https://phabricator.wikimedia.org/T284043
[2] https://phabricator.wikimedia.org/T318496
[3] https://translatewiki.net/w/i.php?search=%22manju+gisun%22&ns8=1&ns1206=1
[4] https://incubator.wikimedia.org/wiki/Wp/mnc/%E1%A1%A0%E1%A0%B5%E1%A1%A0%E1%A1%B3_%E1%A0%A0%E1%A1%B6%E1%A0%A0%E1%A1%A5%E1%A0%A0
> Add Latin script for Manchu (mnc-latn)

- data/language-data.json
I mistakenly merged #314, in which this file was edited manually, and not automatically using the script.
This fixes names that use '/' and removes several
languages and variants of China and Taiwan.
This also adds Ladin "lld" to Italy.
> Automatically recreate data/language-data.json

- data/langdb.yaml
- data/language-data.json
This language was added long ago when mui and plm
were separate codes, and mui was "Musi" and plm
was "Palembang". The code plm was retired in 2008
and the only valid code now is mui, and its autonym according to Ethnologue is "Baso Palembang".
This is also the name most commonly used by the
language's speakers according to the article
Alsamadani, Mardheya; Taibah, Samar (2019).
"Types and Functions of Reduplication in Palembang". Journal of the Southeast Asian Linguistics Society.
> Change mui autonym according to Ethnologue

- data/langdb.yaml
- data/language-data.json
Requested at
https://translatewiki.net/w/i.php?title=Support&oldid=12410268#Translating_Wikicontents_to_Ekpeye
Autonym according to
Ngulube, Isaac (2011). "Ekpeye Orthography".
Orthographies of Nigerian Languages. IX.
> Add Ekpeye (ekp)

- data/langdb.yaml
- data/language-data.json
wlx was recently added with the "waalii" autonym.
The translators asked to change the autonym,
and provided a reliable source:
https://translatewiki.net/w/i.php?title=Support&oldid=12497406#Requesting_Waali_language_with_language_code=wlx_to_be_added_to_Wikimedia
> Rename wlx autonym

- composer.json
- composer.lock
- tests/php/LanguageUtilTest.php
```
Installing dependencies from lock file (including require-dev)
Package operations: 3 installs, 7 updates, 0 removals
- Downloading nikic/php-parser (v5.1.0)
- Downloading phpunit/phpunit (9.6.20)
- Upgrading squizlabs/php_codesniffer (3.7.2 => 3.8.1): Extracting archive
dealerdirect/phpcodesniffer-composer-installer contains a Composer plugin which is currently not in your allow-plugins config. See https://getcomposer.org/allow-plugins
Do you trust "dealerdirect/phpcodesniffer-composer-installer" to execute code and wish to enable it now? (writes "allow-plugins" to composer.json) [y,n,d,?] y
- Installing dealerdirect/phpcodesniffer-composer-installer (v1.0.0): Extracting archive
- Upgrading symfony/polyfill-php80 (v1.29.0 => v1.30.0): Extracting archive
- Installing …
```
> Update PHP dependencies

- data/langdb.yaml
- data/language-data.json
It has been used in core MediaWiki,
so it needs to be in language-data, too.
> Add Tamazight (Latin) (zgh-latn)

- data/langdb.yaml
- data/language-data.json
It was added to core MediaWiki long ago for
unclear reasons, but it was never actually
used for anything, and it's probably
not needed anywhere.
It was already removed from core MediaWiki, too.
ruq-latn and ruq-cyrl should probably be removed,
too, but they were actually used for some things
in core MediaWiki, so that needs to be cleaned up
first.
See also downstream bug:
https://phabricator.wikimedia.org/T357981
> Remove ruq-grek

- data/langdb.yaml
- data/language-data.json
Make it less ambiguous, so that it will be clearly distinct from other pidgin languages, and findable by country name.
This name is used, for example, here:
Beimers, Gerry (2009). Pijin: A Grammar of Solomon Islands Pidgin (PhD thesis). The University of New England. page 26
And can also easily be found in many other sources.
> Update Solomon Islands Pidgin (pis) autonym

- data/langdb.yaml
- data/language-data.json
https://phabricator.wikimedia.org/T356144
> Add Central Kanuri as a full-fledged language

- data/langdb.yaml
- data/language-data.json
Please add the Awajún language, this language is spoken in northern Peru: https://en.wikipedia.org/wiki/Aguaruna_language. Thanks
> Add Awajún (agr)

- composer.json
- composer.lock
Contains all changes to release the Node.js version of the library
1. Update composer dependencies
2. Bump minimum PHP version to 8.0.0
3. Set `config.platform.php` to 8.0.0 to ensure that dependencies of PHP 8+ are installed.
4. `composer audit` did not find any vulnerabilities.
```
$ composer audit
No security vulnerability advisories found.
```
> Prep PHP version for release
